### ISSUE TITLE
New TwinCAT Youtube Channel

### ISSUE THREAD

**Issue by samsaw-dev** [benhar-dev/twincat-resources#1]
Hi Ben! 
Here is another Youtube Channel on TwinCAT 3: [Electrical Automation Hands-On](https://www.youtube.com/channel/UCZqe2O5oBpas73BVdwHTiCA)
Thanks for creating this list! I am curious about what will be collected here in the future.

**Comment by benhar-dev** [comment]
Thank you for your input on this samsaw-dev!  I'm keen to see how it goes too as there are already things on here which I was not aware of before starting.
