### ISSUE TITLE
Curso de OOP IEC 61131-3 PLCs TwinCAT and Codesys

### ISSUE THREAD

**Issue by runtimevic** [benhar-dev/twincat-resources#11]
🐙 Repositorio de GitHub:
👉 https://lnkd.in/d4EmXRaT

📖 Documentación:
👉 https://lnkd.in/de6E_Rbs
👉 https://lnkd.in/d2JUdq-6

lista de videos en Youtube:
https://www.youtube.com/playlist?list=PLEfi_hUmmSjFpfdJ6yw3B9yj7dWHYkHmQ

**Comment by benhar-dev** [comment]
Thank you @runtimevic, is is now in the latest commit #4e3919a
