### ISSUE TITLE
Beckhoff Blog UK (Virtual Visit) is gone

### ISSUE THREAD

**Issue by JacobsonLantern** [benhar-dev/twincat-resources#15]
Just a heads up, Beckhoff Blog UK (www.beckhoffblog.co.uk) / virtual visit is no longer active. Does anybody know where they moved it?

**Comment by benhar-dev** [comment]
Thank you for pointing this out @JacobsonLantern, I'll have a word with the team to find out if they will be relocating it.  If not then we'll add the remaining videos to the Beckhoff AU teachable collection.
