### ISSUE TITLE
Here are a few links to consider adding

### ISSUE THREAD

**Issue by adrianjenkner** [benhar-dev/twincat-resources#16]
Links:
https://www.benediktgeisler.de/en/blog/
https://github.com/bengeisler/TcLog
https://mbc-engineering.github.io/log4TC/index.html
https://github.com/mbc-engineering/log4TC

**Comment by JSGHCOM** [comment]
TcLog is a very useful logging tool, but Log4Tc still doesn't know how to use it after reading the blog

**Comment by benhar-dev** [comment]
Thank you for your input @adrianjenkner
