### ISSUE TITLE
https://automacaoweb.wordpress.com/

### ISSUE THREAD

**Issue by automacaoweb** [benhar-dev/twincat-resources#3]
Hi Ben!

Is possible to include my blog: https://automacaoweb.wordpress.com/

Even though it's in Portuguese, I get hits from all over the world. User can use google translator.

Thank you for your attention.

**Comment by benhar-dev** [comment]
Hi @automacaoweb, I've just had a look and this looks like a fantastic resource. 100% this should be on the list as more people need to see it.  Thank you for your contribution, both with this suggestion and for creating and maintaining the blog too.
