### ISSUE TITLE
fisothemes libraries

### ISSUE THREAD

**Issue by piratecarrot** [benhar-dev/twincat-resources#9]
https://github.com/fisothemes/TwinCat-Dynamic-Collections
https://github.com/fisothemes/TwinCAT-Hashing-Algorithms
https://github.com/fisothemes/TwinCAT-Retentive-Timers
https://github.com/fisothemes/TwinCAT-Abstract-Data-Structures
https://github.com/fisothemes/TwinCAT-Custom-Generic-Data-Type

**Comment by benhar-dev** [comment]
Many thanks @piratecarrot, this is now in the latest commit #4c9ca8d
